# site name
prefixName: 未来は有望です
siteName: 顾一
# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.0/favicon.ico
avatar: https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.0/avatar.jpg
url: https://sakura.hojun.cn
description: 我高喊无爱者自由，可余光还是看向了被爱者
cdn: 
pjax: 1
# 1开启
mathjax: 0

notice: 这是顾某新建的一个小破站
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.5/ASP.net/3.jpg
  - https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.5/2/1.jpg
  - https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.6/6gePhoto/4.jpg
  - https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.6/6gePhoto/chuyin.jpg
  - https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.6/6gePhoto/mingrixiang.jpg
  - https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.6/6gePhoto/nidemingzi.jpg
  - https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.6/6gePhoto/szx.jpg
  - https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.6/6gePhoto/xingkong.jpg
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/353226706?spm_id_from=333.1007.0.0, title: Bilibili, desc: 小顾的B站视频, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/bilibili.jpg}
  - {url: /game/, title: 顾某的爱好, desc: 爱玩的一些游戏, img: https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.3/2/2.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PC端配置
social:
  github: {url: http://github.com/Ghamengde, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/github.png}
  sina: {url: https://weibo.com/?wvr=5&lf=reg, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/sina.png}
  wangyiyun: {url: http://github.com/Ghamengde, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wangyiyun.png}
  zhihu: {url: http://github.com/Ghamengde, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/zhihu.png}
  email: {url: http://github.com/Ghamengde, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/email.svg}
  wechat: {url: /#, qrcode: https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.7/1/qq.png, img: https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.5/picture/QQ.png}
  wechat2: {url: /#, qrcode: https://cdn.jsdelivr.net/gh/Ghamengde/BlogCDN@1.0.7/1/wechat.png, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/Ghamengde, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: 
  alipay: 
  wechat: 
  wechatSQ: 

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

comments:
  use: Waline
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: false # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page

waline:
  serverURL: waline.yourdomain.com    # 填入刚刚得到的后端 URL（必填,根据实际情况填写你自己的域名）
  option:
    locale: {
      nick: '昵称',
      mail: '邮箱',
      link: '你的网站',
      placeholder: '你这么可爱一定会文明评论的吧～(填写邮箱可以收到回复通知哦)',
      requiredMeta: [],
      mailError: '请填写正确的邮件地址',
      sofa: '快来抢占沙发~',
      level0: '锻体',
      level1: '练气',
      level2: '筑基',
      level3: '金丹',
      level4: '元婴',
      level5: '化神',
      }
    emoji: [
        'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tw-emoji',
        'https://cdn.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs',
        'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
        ]